### ISSUE TITLE
Missing dependency - Failure to find org.owasp.webgoat:webgoat-container:jar:6.1.0

### ISSUE THREAD

**Issue by shantisuresh01** [WebGoat/WebGoat-Lessons#25]
Hello,

WebGoat-Lessons from "https://github.com/WebGoat/WebGoat-Lessons.git" did not build.  Included is the "mvn package" output.  Please let me know how I might fix this issue. Thanks!

              -Shanti
---------
localhost:WebGoat-Lessons shanti$  mvn package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] webgoat-plugins-parent
[INFO] common
[INFO] goat-hills-financial
[INFO] access-control-matrix
[INFO] back-doors
[INFO] basic-authentication
[INFO] blind-numeric-sql-injection
[INFO] blind-script
[INFO] blind-string-sql-injection
[INFO] bypass-html-field-restrictions
[INFO] challenge
[INFO] client-side-filtering
[INFO] client-side-validation
[INFO] command-injection
[INFO] concurrency-cart
[INFO] cross-site-scripting
[INFO] csrf-prompt-by-pass
[INFO] csrf-token-by-pass
[INFO] csrf
[INFO] dangerous-eval-injection
[INFO] db-cross-site-scripting
[INFO] db-sql-injection
[INFO] dist
[INFO] dom-injection
[INFO] dom-xss
[INFO] dos-login
[INFO] encoding
[INFO] fail-open-authentication
[INFO] forced-browsing
[INFO] forgot-password
[INFO] hidden-field-tampering
[INFO] how-to-work
[INFO] html-clues
[INFO] http-basics
[INFO] http-only
[INFO] insecure-login
[INFO] java-script-validation
[INFO] json-injection
[INFO] lesson-converter
[INFO] lesson-template-legacy
[INFO] log-spoofing
[INFO] malicious-file-execution
[INFO] multi-level-login1
[INFO] multi-level-login2
[INFO] off-by-one
[INFO] password-strength
[INFO] path-based-access-control
[INFO] phishing
[INFO] reflected-xss
[INFO] remote-admin-flaw
[INFO] role-based-access-control
[INFO] same-origin-policy-protection
[INFO] session-fixation
[INFO] silent-transactions
[INFO] soap-request
[INFO] sql-injection
[INFO] sql-numeric-injection
[INFO] sql-string-injection
[INFO] stored-xss
[INFO] thread-safety-problem
[INFO] trace-xss
[INFO] unchecked-email
[INFO] weak-authentication-cookie
[INFO] weak-session-id
[INFO] ws-sax-injection
[INFO] ws-sql-injection
[INFO] wsdl-scanning
[INFO] xml-injection
[INFO] xpath-injection
[INFO] zip-bomb
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building webgoat-plugins-parent 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:copy (copy-artifact) @ webgoat-plugins-parent ---
[INFO] Configured Artifact: org.owasp.webgoat.lesson:webgoat-plugins-parent:1.0:pom
[INFO] org.owasp.webgoat.lesson:webgoat-plugins-parent:1.0:pom already exists in /Users/shanti/GitHub/target/plugins
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building common 1.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.owasp.webgoat:webgoat-container:jar:6.1.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] webgoat-plugins-parent ............................. SUCCESS [  2.275 s]
[INFO] common ............................................. FAILURE [  0.112 s]
[INFO] goat-hills-financial ............................... SKIPPED
[INFO] access-control-matrix .............................. SKIPPED
[INFO] back-doors ......................................... SKIPPED
[INFO] basic-authentication ............................... SKIPPED
[INFO] blind-numeric-sql-injection ........................ SKIPPED
[INFO] blind-script ....................................... SKIPPED
[INFO] blind-string-sql-injection ......................... SKIPPED
[INFO] bypass-html-field-restrictions ..................... SKIPPED
[INFO] challenge .......................................... SKIPPED
[INFO] client-side-filtering .............................. SKIPPED
[INFO] client-side-validation ............................. SKIPPED
[INFO] command-injection .................................. SKIPPED
[INFO] concurrency-cart ................................... SKIPPED
[INFO] cross-site-scripting ............................... SKIPPED
[INFO] csrf-prompt-by-pass ................................ SKIPPED
[INFO] csrf-token-by-pass ................................. SKIPPED
[INFO] csrf ............................................... SKIPPED
[INFO] dangerous-eval-injection ........................... SKIPPED
[INFO] db-cross-site-scripting ............................ SKIPPED
[INFO] db-sql-injection ................................... SKIPPED
[INFO] dist ............................................... SKIPPED
[INFO] dom-injection ...................................... SKIPPED
[INFO] dom-xss ............................................ SKIPPED
[INFO] dos-login .......................................... SKIPPED
[INFO] encoding ........................................... SKIPPED
[INFO] fail-open-authentication ........................... SKIPPED
[INFO] forced-browsing .................................... SKIPPED
[INFO] forgot-password .................................... SKIPPED
[INFO] hidden-field-tampering ............................. SKIPPED
[INFO] how-to-work ........................................ SKIPPED
[INFO] html-clues ......................................... SKIPPED
[INFO] http-basics ........................................ SKIPPED
[INFO] http-only .......................................... SKIPPED
[INFO] insecure-login ..................................... SKIPPED
[INFO] java-script-validation ............................. SKIPPED
[INFO] json-injection ..................................... SKIPPED
[INFO] lesson-converter ................................... SKIPPED
[INFO] lesson-template-legacy ............................. SKIPPED
[INFO] log-spoofing ....................................... SKIPPED
[INFO] malicious-file-execution ........................... SKIPPED
[INFO] multi-level-login1 ................................. SKIPPED
[INFO] multi-level-login2 ................................. SKIPPED
[INFO] off-by-one ......................................... SKIPPED
[INFO] password-strength .................................. SKIPPED
[INFO] path-based-access-control .......................... SKIPPED
[INFO] phishing ........................................... SKIPPED
[INFO] reflected-xss ...................................... SKIPPED
[INFO] remote-admin-flaw .................................. SKIPPED
[INFO] role-based-access-control .......................... SKIPPED
[INFO] same-origin-policy-protection ...................... SKIPPED
[INFO] session-fixation ................................... SKIPPED
[INFO] silent-transactions ................................ SKIPPED
[INFO] soap-request ....................................... SKIPPED
[INFO] sql-injection ...................................... SKIPPED
[INFO] sql-numeric-injection .............................. SKIPPED
[INFO] sql-string-injection ............................... SKIPPED
[INFO] stored-xss ......................................... SKIPPED
[INFO] thread-safety-problem .............................. SKIPPED
[INFO] trace-xss .......................................... SKIPPED
[INFO] unchecked-email .................................... SKIPPED
[INFO] weak-authentication-cookie ......................... SKIPPED
[INFO] weak-session-id .................................... SKIPPED
[INFO] ws-sax-injection ................................... SKIPPED
[INFO] ws-sql-injection ................................... SKIPPED
[INFO] wsdl-scanning ...................................... SKIPPED
[INFO] xml-injection ...................................... SKIPPED
[INFO] xpath-injection .................................... SKIPPED
[INFO] zip-bomb ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.010 s
[INFO] Finished at: 2015-08-15T16:10:52-04:00
[INFO] Final Memory: 15M/220M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project common: Could not resolve dependencies for project org.owasp.webgoat.lesson:common:jar:1.0: Failure to find org.owasp.webgoat:webgoat-container:jar:6.1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :common
---------

**Comment by nbaars** [comment]
Hi Shanti,

The webgoat-container dependency is not yet available in the Maven central repository(will be soon), so in order to build the lessons you first need to build the webgoat-container project on your local machine (only once). This project can be found here: https://github.com/WebGoat/WebGoat

Kind regards,
--Nanne

**Comment by shantisuresh01** [comment]
Thanks so much!  I appreciate the note.  I tried to change the
WebGoat-Lessons/pom.xml to point to the local "system" scoped dependency
for the container jar.  But that didn't work either.  I have attached the
modified pom.xml.

Also, I put the lessons under WebGoar-master as follows:

/Users/shanti/dTools/dWebGoat/dWebGoat_6.1/WebGoat-master/WebGoat-Lessons-master/


Will this structure work okay?


Thanks,

Best Regards,

                        -Shanti

**Comment by nbaars** [comment]
Hi Shanti,

Changed my local repository to a new location, performed the following steps:

1. git clone webgoat
2. mvn clean install
3. git clone webgoat-lessons
4. mvn clean install

This worked, also changed the version of webgoat this worked. Not sure why it does not work, does it work when you specify the `-o` switch?

The lessons should be placed in the following directory: WebGoat\src\main\webapp\plugin_lessons
Then you are able to run: mvn -pl webgoat-container tomcat7:run-war

Make sure you got the latest update of the project we recently moved to a multiproject Maven project.

--Nanne

**Comment by shantisuresh01** [comment]
Hi Nanne,

The build worked like a charm!  Thank you so much!  I had a bunch of
interviewing this week and could not respond earlier.  I created a shell
script as follows and had a typo and so it bombed the first two times I
tried it.  So I wanted to look at it when I had a chance.  It works like
you said.  Here it is:

-----------intall_WebGoat.sh:

#!/bin/sh


GITHUB_HOME=/Users/shanti/GitHub

cd $GITHUB_HOME

git clone https://github.com/WebGoat/WebGoat.git

sleep  10

cd WebGoat

mvn clean install

cd $GITHUB_HOME

git clone https://github.com/WebGoat/WebGoat-Lessons.git

sleep  10

cd WebGoat-Lessons

mvn clean install

cd $GITHUB_HOME/WebGoat

mvn -pl webgoat-container tomcat7:run-war
----------

Thank you, greatly!

Best Regards,

                        -Shanti

**Comment by shantisuresh01** [comment]
Oops!  Sorry!   Upon invoking WebGoat, I see no lessons.

The lessons are in the wrong place.  Let me do this correctly by putting
the lessons in:

WebGoat/src/main/webapp/plugin_lessons/

I don't find a WebGoat/src/ directory.  There is a "src/ under "
WebGoat/webgoat-container/".

Would it be possible for you to modify my shell script and let me know if
the following is correct?  Is this something you are thinking of?:

---------install_WebGoat6.1.sh-----

#!/bin/sh


WEBGOAT_HOME=/Users/shanti/GitHub

cd $WEBGOAT_HOME

git clone https://github.com/WebGoat/WebGoat.git

sleep  5

cd WebGoat

mvn clean install


LESSONS_HOME=/Users/shanti/GitHub/WebGoat/webgoat-container/src/main/resources/plugin_lessons/

mkdir $LESSONS_HOME

cd $LESSONS_HOME

git clone https://github.com/WebGoat/WebGoat-Lessons.git

mvn clean install

cd $GITHUB_HOME/WebGoat

mvn -pl webgoat-container tomcat7:run-war

--------

Thanks!

Best Regards,

                        -Shanti

**Comment by nbaars** [comment]
>Upon invoking WebGoat, I see no lessons.
Correct this is a known issue, see WebGoat/WebGoat#32 for this. For now you can make it work by not copying all the lessons then the menu will be shown.

>The lessons are in the wrong place
Correct the lessons should be placed `WebGoat/webgoat-container/src/main/webapp/plugin_lessons`.
The `README.md` at `WebGoat/WebGoat` has been updated recently

>Would it be possible for you to modify my shell script and let me know if the following is correct
We have a Travis CI script for this which is used to create a new release I think you can use the commands directly into your script. You can find the script in `WebGoat/WebGoat/.travis.yml

--Nanne

**Comment by shantisuresh01** [comment]
Hi Nanne,

Thank you for the tips.  Following those tips and also the TRAVIS file, I
got ahead.  The lessons show up.  But something is still amiss.  HTTP
Basics is giving a null pointer exception.  Some of the other lessons seem
to be working.

I have attached a screen-shot.   I have also attached my modified shell
script.

Thanks,

Best Regards,

                        -Shanti

**Comment by shantisuresh01** [comment]
Sorry,

I had a "mvm package" command before I started tomcat.


Best Regards,

                        -Shanti

**Comment by mayhew64** [comment]
The null pointer is due to a different problem and not your build.  Please feel free to keep reporting issues you see.  It would be better to open up new issues for the problems.  Thanks!

**Comment by nbaars** [comment]
see WebGoat/WebGoat#47 is fixed
