### ISSUE TITLE
Some lessons don't resolve

### ISSUE THREAD

**Issue by shantisuresh01** [WebGoat/WebGoat-Lessons#27]
Greetings,

Thanks for your efforts at restructuring WebGoat.  I wiped out my local repository and cloned and built the latest code after Nanne's update.  Some links are still erroring out.  For e.g.:
    - How to work with WebGoat
    - How to create a Legacy Lesson
    - Http Basics
    - Bypass a Path Based Access Control Scheme

While some are working:
    - Using an Access Control Matrix

Is there a manual dependency I can add or adjust my classpath to so I can resolve this error?  IThe "webgoat-container" does not have an error log; only an access log.

Thanks,

                 -Shanti

![screen shot 2015-08-25 at 3 05 48 pm](https://cloud.githubusercontent.com/assets/12873036/9476604/8437b120-4b3b-11e5-979f-2c24fc5a429b.png)
![screen shot 2015-08-25 at 3 05 32 pm](https://cloud.githubusercontent.com/assets/12873036/9476603/84360ab4-4b3b-11e5-8302-e24f252ff2f7.png)
![screen shot 2015-08-25 at 3 04 57 pm](https://cloud.githubusercontent.com/assets/12873036/9476605/8438aec2-4b3b-11e5-9262-76648754df6b.png)

**Comment by nbaars** [comment]
Hi,

The problem has been fixed, see  WebGoat/WebGoat#53 
Waiting for a pull request to be merged but I will close this issue for now.

--Nanne
