### ISSUE TITLE
CSRF hints suggest embedding MVC links

### ISSUE THREAD

**Issue by ilatypov** [WebGoat/WebGoat-Lessons#38]
The forge messages need to abuse the img src tag to generate a GET request along with the cookie.

But the new MVC links would require interpreting their output by the browser which would only then execute the necessary servlet.

I wonder if the hints should still mention the one-request links "attack?Screen=XXX&menu=YYY".

**Comment by misfir3** [comment]
Merged back in November, closing this. Re-open or create new if issue re-appears or is found to be not truly fixed.
