### ISSUE TITLE
HttpBasics solution should be updated

### ISSUE THREAD

**Issue by alexhudici** [WebGoat/WebGoat-Lessons#44]
The solution makes reference to WebScarab which, according to the [OWASP wiki](https://www.owasp.org/index.php/Category:OWASP_WebScarab_Project) is no longer being maintained. Most people would probably have ZAP installed anyway and the instructions to install WebScarab on the wiki are not very clear.

**Comment by misfir3** [comment]
HTTP Basics had been updated it appears and I fixed a link (was still going to scarab) in the fail-open-authentication lesson.
