### ISSUE TITLE
Please sync branches with webgoat-container

### ISSUE THREAD

**Issue by rusboy** [WebGoat/WebGoat-Lessons#55]
Guys,

I've tried to use existing lessons with tag 7.0.1 of webgoat project.. 
But I've got an issue...
When I compiled the existing lessions(from master branch), I got error maven error about webgoat-container 7.0.-snapshot is not found

Eventually, to fix it I've updated version in "root" pom.xml

I think, would be great if webgoat-lession project includes (in develop branch and tags at least) version that is same with webgoat-container.. then "root" pom.xml can include correct webgoat-container version..

Thanks..

P.S. if you need some assistance with translation to Russian language, I can assist. Let me know.

**Comment by mayhew64** [comment]
Yes, translation to Russian would be great.  As part of the translation process, we also need to extract out the english phrases into the lesson specific properties.  Are you interested in helping with that as well?

**Comment by rusboy** [comment]
"Are you interested in helping with that as well?"
Yep, why not. Anyway I'm using the application to learn vulners.

**Comment by boyobejamin** [comment]
I had a similar issue. When compiling the lessons, I received the following error.
`[ERROR] Failed to execute goal on project common: Could not resolve dependencies for project org.owasp.webgoat.lesson:common:jar:1.0: Could not find artifact org.owasp.webgoat:webgoat-container:jar:7.0-SNAPSHOT -> [Help 1]`

When doing an 'ls WebGoat/webgoat-container/target/' I see that the file is called 7.1-SPANSHOT.jar. Clearing the Maven cache and setting line 102 in WebGoat-Lessons/pom.xml from 
`<version>7.0-SNAPSHOT</version>` to `<version>7.1-SNAPSHOT</version>` worked for me.

**Comment by nbaars** [comment]
Version issue and the `sh` issue are both fixed, closing this issue
