### ISSUE TITLE
Incorrect success message in Ajax security -> Dangerous Use of Eval lesson

### ISSUE THREAD

**Issue by rusboy** [WebGoat/WebGoat-Lessons#58]
![image](https://cloud.githubusercontent.com/assets/3583960/13007562/3d579688-d1a2-11e5-8aec-5ed48f19ef45.png)

**Comment by rusboy** [comment]
Same issue with Password Strength lesson

![image](https://cloud.githubusercontent.com/assets/3583960/13007781/8c701000-d1a3-11e5-8bb6-f9ebce0e2a6e.png)

**Comment by rusboy** [comment]
+ Forgot Password
![image](https://cloud.githubusercontent.com/assets/3583960/13007918/593463ca-d1a4-11e5-971b-edd1c11ade98.png)

**Comment by rusboy** [comment]
I'll fix this one

**Comment by rusboy** [comment]
So.. we see "????" - because WebSession.js gets from request Ru-ru location..  
header of my request includes the location.. it looks so "Accept-Language:ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4"

I see here 2 issues, that are related with webgoat-container:
1. ???? - is incorrect translation to Russian. Need to fix.
2. Switching to location from request..

For second issue I'll open pull request.. 
For first one I'll create a new issue in webgoat project

I hope, you are okey

**Comment by nbaars** [comment]
Closing this issue because in WebGoat/WebGoat#199 it is marked as solved.
